name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the source code
      uses: actions/checkout@v3
    - name: Build the dev docker image
      run: docker build . --file Dockerfile.dev --tag docker-react:dev
  test-dev:
    runs-on: ubuntu-latest
    needs: build-dev
    steps:
    - name: Test the dev docker image
      run: docker run -e CI=true docker-react:dev npm run test a
  build-release:
    runs-on: ubuntu-latest
    needs: test-dev
    steps:
    - name: Build the release docker image
      run: docker build . --file Dockerfile --tag docker-react:latest
