name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag sweetyoru/docker-react
    - name: Test the docker image
      run: docker run sweetyoru/docker-react npm run test -- --coverage
